# Generated by Django 4.0.4 on 2022-05-06 16:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sarlacc', '0003_remove_wxsproject_project_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXSProcessedData',
            fields=[
                ('processeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.processeddata')),
                ('RGcrams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=None)),
                ('ready_bam', models.CharField(blank=True, max_length=1)),
                ('gvcf', models.CharField(blank=True, max_length=1)),
                ('coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('freemix', models.DecimalField(blank=True, decimal_places=5, max_digits=6)),
                ('titv', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
            ],
            bases=('sarlacc.processeddata',),
        ),
        migrations.CreateModel(
            name='WXSProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.project')),
                ('center', models.CharField(max_length=10)),
                ('wxs', models.CharField(choices=[('G', 'WGS'), ('E', 'WES'), ('B', 'WGS_WES'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
            bases=('sarlacc.project',),
        ),
        migrations.CreateModel(
            name='WXSRawData',
            fields=[
                ('rawdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.rawdata')),
                ('type', models.CharField(choices=[('I', 'interleaved fastq'), ('C', 'cram'), ('B', 'bam'), ('P', 'paired-end fastq')], max_length=1)),
                ('flowcell', models.CharField(max_length=10)),
                ('lane', models.CharField(max_length=1)),
            ],
            bases=('sarlacc.rawdata',),
        ),
        migrations.CreateModel(
            name='WXSRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.run')),
                ('pipeline', models.CharField(max_length=8)),
                ('gpu', models.BooleanField(default=False)),
                ('dbsnp', models.CharField(max_length=4)),
                ('reference_genome', models.CharField(choices=[('h', 'hg19'), ('7', 'GRCh37'), ('8', 'GRCh38'), ('T', 'T2T'), ('U', 'Unknown')], default='U', max_length=1)),
                ('align_version', models.CharField(blank=True, max_length=20)),
                ('gatk_version', models.CharField(blank=True, max_length=20)),
                ('samtools_version', models.CharField(blank=True, max_length=20)),
                ('run_type', models.CharField(choices=[('P', 'Padded Exome'), ('E', 'Exome'), ('G', 'Genome')], default='P', max_length=1)),
                ('bedtools_version', models.CharField(blank=True, max_length=20)),
                ('picard_version', models.CharField(blank=True, max_length=20)),
            ],
            bases=('sarlacc.run',),
        ),
        migrations.CreateModel(
            name='WXSSample',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.sample')),
                ('barcode', models.CharField(max_length=10)),
                ('series', models.CharField(max_length=15)),
            ],
            bases=('sarlacc.sample',),
        ),
    ]
