# Generated by Django 4.0.4 on 2022-05-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wxsrun',
            old_name='align_version',
            new_name='aligner_version',
        ),
    ]
