# Generated by Django 4.0.4 on 2022-05-04 18:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pheno_id', models.CharField(max_length=20, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('other_ids', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alias', related_query_name='aliases', to='sarlacc.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('file_basename', models.CharField(blank=True, max_length=30)),
                ('directory', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('basename', models.CharField(max_length=30)),
                ('directory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_collected', models.DateField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', related_query_name='sample', to='sarlacc.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', related_query_name='sample', to='sarlacc.project')),
            ],
        ),
        migrations.CreateModel(
            name='WXSProcessedData',
            fields=[
                ('processeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.processeddata')),
                ('RGcrams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=None)),
                ('ready_bam', models.CharField(blank=True, max_length=1)),
                ('gvcf', models.CharField(blank=True, max_length=1)),
                ('coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('freemix', models.DecimalField(blank=True, decimal_places=5, max_digits=6)),
                ('titv', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
            ],
            bases=('sarlacc.processeddata',),
        ),
        migrations.CreateModel(
            name='WXSProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.project')),
                ('center', models.CharField(max_length=10)),
                ('wxs', models.CharField(choices=[('G', 'WGS'), ('E', 'WES'), ('B', 'WGS_WES'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
            bases=('sarlacc.project',),
        ),
        migrations.CreateModel(
            name='WXSRawData',
            fields=[
                ('rawdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.rawdata')),
                ('type', models.CharField(choices=[('I', 'interleaved fastq'), ('C', 'cram'), ('B', 'bam'), ('P', 'paired-end fastq')], max_length=1)),
                ('flowcell', models.CharField(max_length=10)),
                ('lane', models.CharField(max_length=1)),
            ],
            bases=('sarlacc.rawdata',),
        ),
        migrations.CreateModel(
            name='WXSRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.run')),
                ('pipeline', models.CharField(max_length=8)),
                ('gpu', models.BooleanField(default=False)),
                ('reference_genome', models.CharField(choices=[('h', 'hg19'), ('7', 'GRCh37'), ('8', 'GRCh38'), ('T', 'T2T'), ('U', 'Unknown')], default='U', max_length=1)),
                ('align_version', models.CharField(blank=True, max_length=20)),
                ('gatk_version', models.CharField(blank=True, max_length=20)),
                ('samtools_version', models.CharField(blank=True, max_length=20)),
                ('run_type', models.CharField(choices=[('P', 'Padded Exome'), ('E', 'Exome'), ('G', 'Genome')], default='P', max_length=1)),
                ('bedtools_version', models.CharField(blank=True, max_length=20)),
                ('picard_version', models.CharField(blank=True, max_length=20)),
            ],
            bases=('sarlacc.run',),
        ),
        migrations.CreateModel(
            name='WXSSample',
            fields=[
                ('sample_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sarlacc.sample')),
                ('barcode', models.CharField(max_length=10)),
                ('series', models.CharField(max_length=15)),
            ],
            bases=('sarlacc.sample',),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raw_data', to='sarlacc.sample'),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processed_data', to='sarlacc.run'),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='processed_data', to='sarlacc.sample'),
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_effective', models.DateField()),
                ('cohort', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('race', models.CharField(choices=[('W', 'White'), ('B', 'Black/African American'), ('A', 'Asian'), ('N', 'American Indian/Native American'), ('M', 'More than one race'), ('P', 'Native Hawaiian or Other Pacific Islander'), ('U', 'Unknown')], default='U', max_length=1)),
                ('ethnicity', models.CharField(choices=[('H', 'Hispanic or Latinx'), ('N', 'Not Hispanic or Latinx'), ('U', 'Unknown')], default='U', max_length=1)),
                ('apoe', models.CharField(choices=[('22', '22'), ('23', '23'), ('24', '24'), ('33', '33'), ('34', '34'), ('44', '44'), ('NA', 'NA'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('education', models.PositiveSmallIntegerField()),
                ('final_cc_status', models.CharField(choices=[('AD', (('AD', 'AD'), ('AAN', 'ADAD_Affected_Non_carrier'), ('AAC', 'ADAD_Affected_carrier'), ('ANC', 'ADAD_Non_carrier'), ('APC', 'ADAD_Presymptomatic_carrier'), ('NAD', 'Neuro_AD'), ('NAD', 'Neuro_AD_DLB'), ('NAF', 'Neuro_AD_FTD'), ('NAP', 'Neuro_AD_PD'), ('NPA', 'Neuro_PreSymptomatic_AD'), ('DEM', 'Dementia'))), ('Control', (('AUN', 'ADAD_Unaffected_Non_carrier'), ('CO', 'CO'), ('MUN', 'MAPT_Unaffected_Non_carrier'), ('NCO', 'Neuro_CO'), ('OCO', 'OT(CO)'), ('PUN', 'PGRN_Unaffected_Non_carrier'))), ('Other', (('C9+', 'C9ORF72+'), ('MAN', 'MAPT_Affected_Non_carrier'), ('MAC', 'MAPT_Affected_carrier'), ('MNC', 'MAPT_Non_carrier'), ('MPC', 'MAPT_Presymptomatic_carrier'), ('MC', 'MAPT_carrier'), ('PAN', 'PGRN_Affected_Non_carrier'), ('PAC', 'PGRN_Affected_carrier'), ('PNC', 'PGRN_Non_carrier'), ('PPC', 'PGRN_Presymptomatic_carrier'), ('PC', 'PGRN_carrier'), ('NAL', 'Neuro_ALS'), ('NDL', 'Neuro_DLB'), ('NFT', 'Neuro_FTD'), ('NOT', 'Neuro_OT'), ('NPD', 'Neuro_PD'), ('NPS', 'Neuro_PSP'), ('PRY', 'Neuro_Parry'), ('OT', 'OT'), ('DLB', 'DLB'), ('FTD', 'FTD'), ('PD', 'PD'))), ('CHECK', (('N19', 'CC_npthprim19'), ('L2P', 'LRRK2_positive'))), ('NO', (('NOS', 'NO-SHARING'), ('OSC', 'OSC'), ('UNK', 'Unknown')))], default='UNK', max_length=3)),
                ('cdr_final', models.CharField(choices=[('A', '0'), ('B', '0.5'), ('C', '1'), ('D', '2'), ('E', '3'), ('U', 'Unknown')], default='U', max_length=1)),
                ('cdr_expiration', models.CharField(choices=[('A', '0'), ('B', '0.5'), ('C', '1'), ('D', '2'), ('E', '3'), ('U', 'Unknown')], default='U', max_length=1)),
                ('age_onset', models.PositiveSmallIntegerField(blank=True)),
                ('age_at_last', models.PositiveSmallIntegerField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phenotype', related_query_name='phenotypes', to='sarlacc.participant')),
            ],
        ),
    ]
