# Generated by Django 4.0.4 on 2022-05-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarlacc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='other_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alias', related_query_name='aliases', to='sarlacc.participant'),
        ),
    ]
