# Generated by Django 4.0.4 on 2022-05-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarlacc', '0002_alter_participant_other_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxsproject',
            name='project_ptr',
        ),
        migrations.RemoveField(
            model_name='wxsrawdata',
            name='rawdata_ptr',
        ),
        migrations.RemoveField(
            model_name='wxsrun',
            name='run_ptr',
        ),
        migrations.RemoveField(
            model_name='wxssample',
            name='sample_ptr',
        ),
        migrations.DeleteModel(
            name='WXSProcessedData',
        ),
        migrations.DeleteModel(
            name='WXSProject',
        ),
        migrations.DeleteModel(
            name='WXSRawData',
        ),
        migrations.DeleteModel(
            name='WXSRun',
        ),
        migrations.DeleteModel(
            name='WXSSample',
        ),
    ]
