# Generated by Django 4.0.4 on 2022-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarlacc', '0003_remove_wxsproject_project_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phenotype',
            old_name='name',
            new_name='id_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pheno_id',
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='cohort',
            field=models.CharField(max_length=15),
        ),
    ]
